version: '3.7'

services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: passin-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=passin-db
    networks:
      - passin
  
  api-passin:
    build:
      context: .
    container_name: api-passin
    ports:
      - 3001:3333
    environment:
      - DATABASE_URL=
      - API_BASE_URL=http://localhost:3333
    depends_on:
      - postgres
    networks:
      - passin
networks:
  passin:
    driver: bridge