apiVersion: apps/v1
kind: Deployment

metadata:
  name: passin-deployment
  labels:
    app: passin
    
spec:
  replicas: 5
  selector:
    matchLabels:
      app: passin
      
  template:
    metadata:
      labels:
        app: passin
        
    spec:
      containers:
      - name: passin
        image: nicklimadev/passin-app:caa6d4a
        env:
        - name: DATABASE_URL
          value:
        - name: API_BASE_URL
          value: "http://localhost:3333"
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 400m
            memory: 512Mi
        ports:
        - containerPort: 3333